// Reads dist/index.html (single-file Vite build) and writes it into
// ../src/components/webMapBuild.ts as `export const MAP_HTML = "..."`.
// JSON.stringify is used so backticks / ${} / quotes inside the HTML can never
// break the generated TypeScript file.

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const HTML_PATH = resolve(__dirname, '..', 'dist', 'index.html');
const OUT_PATH = resolve(
  __dirname,
  '..',
  '..',
  'src',
  'components',
  'webMapBuild.ts'
);

const html = readFileSync(HTML_PATH, 'utf8');

const banner =
  '// AUTO-GENERATED by webProject/scripts/inlineHtml.mjs.\n' +
  '// Do not edit by hand. Run `npm run build` inside webProject to regenerate.\n';

const fileContent = `${banner}\nexport const MAP_HTML = ${JSON.stringify(
  html
)};\n`;

writeFileSync(OUT_PATH, fileContent, 'utf8');

const sizeKb = (statSync(HTML_PATH).size / 1024).toFixed(1);
console.log(
  `[inlineHtml] wrote ${OUT_PATH} (source: ${HTML_PATH}, ${sizeKb} kB)`
);
